# Generated by Django 4.0.5 on 2022-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_history_inspection_alter_history_request_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history_request',
            options={'ordering': ['-created_date'], 'verbose_name': 'История заявок', 'verbose_name_plural': 'История заявок'},
        ),
        migrations.AddField(
            model_name='history_request',
            name='air_assembly',
            field=models.BooleanField(default=False, verbose_name='Воздушная система'),
        ),
        migrations.AddField(
            model_name='history_request',
            name='air_assembly_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='history_request',
            name='another',
            field=models.BooleanField(default=False, verbose_name='Другое'),
        ),
        migrations.AddField(
            model_name='history_request',
            name='another_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='history_request',
            name='electrical_assembly',
            field=models.BooleanField(default=False, verbose_name='Электрический узел'),
        ),
        migrations.AddField(
            model_name='history_request',
            name='electrical_assembly_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='history_request',
            name='mehanical_assembly',
            field=models.BooleanField(default=False, verbose_name='Механический узел'),
        ),
        migrations.AddField(
            model_name='history_request',
            name='mehanical_assembly_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AddField(
            model_name='history_request',
            name='oil_assembly',
            field=models.BooleanField(default=False, verbose_name='Масляная система'),
        ),
        migrations.AddField(
            model_name='history_request',
            name='oil_assembly_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='history_inspection',
            name='air_assembly',
            field=models.BooleanField(default=False, verbose_name='Воздушная система'),
        ),
        migrations.AlterField(
            model_name='history_inspection',
            name='air_assembly_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='history_inspection',
            name='all_ok',
            field=models.BooleanField(default=False, verbose_name='Все в порядке'),
        ),
        migrations.AlterField(
            model_name='history_inspection',
            name='another',
            field=models.BooleanField(default=False, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='history_inspection',
            name='another_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='history_inspection',
            name='electrical_assembly',
            field=models.BooleanField(default=False, verbose_name='Электрический узел'),
        ),
        migrations.AlterField(
            model_name='history_inspection',
            name='electrical_assembly_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='history_inspection',
            name='mehanical_assembly',
            field=models.BooleanField(default=False, verbose_name='Механический узел'),
        ),
        migrations.AlterField(
            model_name='history_inspection',
            name='mehanical_assembly_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='history_inspection',
            name='oil_assembly',
            field=models.BooleanField(default=False, verbose_name='Масляная система'),
        ),
        migrations.AlterField(
            model_name='history_inspection',
            name='oil_assembly_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание проблемы'),
        ),
    ]
