# Generated by Django 4.0.5 on 2022-07-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_history_request_compressor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_request',
            name='air_assembly_shut',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Решение проблемы'),
        ),
        migrations.AddField(
            model_name='history_request',
            name='another_shut',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Решение проблемы'),
        ),
        migrations.AddField(
            model_name='history_request',
            name='electrical_assembly_shut',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Решение проблемы'),
        ),
        migrations.AddField(
            model_name='history_request',
            name='mehanical_assembly_shut',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Решение проблемы'),
        ),
        migrations.AddField(
            model_name='history_request',
            name='oil_assembly_shut',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Решение проблемы'),
        ),
    ]
