# Generated by Django 4.0.2 on 2022-05-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Compressor_lable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('manufacturer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compressor_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('Винтовой', 'screw'), ('Поршневой', 'piston'), ('Спиральный', 'spiral')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desktop.company')),
            ],
        ),
        migrations.CreateModel(
            name='Compressor_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('drive', models.CharField(max_length=50)),
                ('nutrition', models.CharField(max_length=50)),
                ('cooling', models.CharField(max_length=50)),
                ('max_turnover', models.IntegerField()),
                ('min_turnover', models.IntegerField()),
                ('noise_level', models.IntegerField()),
                ('tank_oil', models.IntegerField()),
                ('effeciency', models.IntegerField()),
                ('max_pressure', models.IntegerField()),
                ('engine_power', models.IntegerField()),
                ('compressor_lable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desktop.compressor_lable')),
                ('compressor_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desktop.compressor_type')),
            ],
        ),
        migrations.CreateModel(
            name='Compressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('compressor_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desktop.compressor_model')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desktop.room')),
            ],
        ),
    ]
